failover health and diagnostics additions
osisoft/PI-Adapter pull request #106
Opened 2022-04-25 15:44 UTC by akiaei

Failover health updates from WI 231700. 
Also we might consider updating the example picture for AF structure in health-and-diagnostics.md to include a failover health asset. What do you think? Example below

![image](https://user-images.githubusercontent.com/43865349/165124640-87408a6c-fe8f-49d4-9c5d-6620fc604bef.png)

2022-04-26 16:28 UTC, bningOSI commented on shared-content/diagnostics/failover-status.md
> +| **FailoverStatus**  | `float` | . Value between 0 and 100 indicating the adapter's overall connectivity to each data source. 100 is 'Good' and all data source connections were successful. 0 is 'Bad
does this "." belong to the entry above?

2022-04-26 19:46 UTC, akiaei commented on shared-content/diagnostics/failover-status.md
> +| **FailoverStatus**  | `float` | . Value between 0 and 100 indicating the adapter's overall connectivity to each data source. 100 is 'Good' and all data source connections were successful. 0 is 'Bad
Nope, just a typo. I'll push up a fix, good catch

2022-04-26 21:47 UTC, rmuolic commented on shared-content/diagnostics/failover-status.md
> +| **FailoverStatus**  | `float` | Value between 0 and 100 indicating the adapter's overall connectivity to each data source. 100 is 'Good' and all data source connections were successful. 0 is 'Bad'
```suggestion
| **FailoverStatus**  | `float` | Value between 0 and 100 indicating the adapter's overall connectivity to each data source. 100 is 'Good' and all data source connections are successful. 0 is 'Bad' and no data is being collected.|
```

2022-04-26 21:48 UTC, rmuolic commented on shared-content/diagnostics/failover-status.md
> +| **FailoverRole**  | `string` | Current role of the failover instance. When the adapter assumes `Primary` role it is egressing data. In the `Secondary` role, the adapter will not be egressing data t
```suggestion
| **FailoverRole**  | `string` | Current role of the failover instance. When the adapter assumes the `Primary` role, it is egressing data. If the adapter is set to the `Secondary` role, it does not egress data to the failover endpoint, but it may retain a cache of data if the failover mode is set to `Hot`.
```

2022-04-26 21:48 UTC, rmuolic requested changes
Minor changes.

2022-04-27 15:08 UTC, akiaei commented on shared-content/diagnostics/failover-status.md
> +| **FailoverStatus**  | `float` | Value between 0 and 100 indicating the adapter's overall connectivity to each data source. 100 is 'Good' and all data source connections were successful. 0 is 'Bad'
updated to present tense

2022-04-27 23:50 UTC, rmuolic approved these changes

2022-04-27 23:51 UTC, rmuolic commented
@akiaei I have approved this PR. In regards, to the updated AF structure image for the health-and-diagnostics.md topic I'll create another PR once this PR is merged into v1.6.

2022-04-28 00:09 UTC, bningOSI approved these changes

2022-04-28 00:10 UTC, rmuolic approved these changes

2022-04-28 00:11 UTC, merged