secrets doc
osisoft/PI-Adapter pull request #111
Opened 2022-06-17 21:49 UTC by kshuOSIsoft

user guide for secrets rest. 

demo can be found here: https://aveva-my.sharepoint.com/:v:/p/xiaoli_tang/EVk2eaKHcH9MidX_PqpTzaQBF8_V5l1brKr6567iiPMIpQ

design doc: https://aveva.sharepoint.com/:w:/r/sites/PI-Engineering/architecture/_layouts/15/Doc.aspx?sourcedoc=%7B9FFD35F5-6459-4410-8E7F-668D72A4C410%7D&file=Design%20Document%20%20-%20Edge%20Secret%20Manageability.docx&action=default&mobileredirect=true&cid=c82c651b-6750-4555-aef1-e2d32292d98f

2022-06-20 18:02 UTC, rmuolic commented on shared-content/management/secrets.md
> +Adapter Framework-based edge systems use secrets when authenticating with sources and destinations. All secrets are encrypted and stored in the management_secrets.json file and can be referenced by u
```suggestion
Adapter Framework-based edge systems use secrets when authenticating with sources and destinations. All secrets are encrypted and stored in the `management_secrets.json` file and are referenced by using their ID in other configurations' protected fields (e.g. "clientSecret" : "{{Secret#2}}"). 
```

2022-06-20 18:05 UTC, rmuolic commented on shared-content/management/secrets.md
> +The full schema definition for the egress endpoint configuration is in the `Management_Secrets_schema.json`  file located in one of the following folders:
```suggestion
The full schema definition for the egress endpoint configuration is in the `Management_Secrets_schema.json` file located in one of the following folders:
```
```suggestion
The full schema definition for the egress endpoint configuration is in the `Management_Secrets_schema.json`  file located in one of the following folders:
```

2022-06-20 18:07 UTC, rmuolic commented on shared-content/management/secrets.md
> +| api/v1/management/secrets | PUT | Creates or replaces entire secrests configuration |
```suggestion
| api/v1/management/secrets | PUT | Creates or replaces entire secrets configuration |
```
```suggestion
| api/v1/management/secrets | PUT | Creates or replaces entire secrests configuration |
```

2022-06-20 18:16 UTC, rmuolic requested changes
minor suggestions

2022-06-20 18:17 UTC, rmuolic commented
@kshuOSIsoft is the secrets config a feature for the current adapter framework 1.5 or 1.6?

2022-06-20 18:21 UTC, kshuOSIsoft commented
> @kshuOSIsoft is the secrets config a feature for the current adapter framework 1.5 or 1.6?

1.6

2022-06-20 18:23 UTC, rmuolic commented
> > @kshuOSIsoft is the secrets config a feature for the current adapter framework 1.5 or 1.6?
> 
> 1.6

Thanks, I've updated the base to 1.6

2022-06-20 18:41 UTC, rmuolic approved these changes

2022-06-20 21:02 UTC, akiaei requested changes

2022-06-20 21:02 UTC, akiaei commented on shared-content/management/secrets.md
> +
I think we should add an additional note about the mask and how it can be used to update other parameters without changing the secret value

2022-06-20 21:05 UTC, akiaei commented on shared-content/management/secrets.md
> +| api/v1/management/secrets | GET | Returns entire secrets configuration (secret values will be *s) |
what do you think about changing this to masked or hidden @rmuolic? 
```suggestion
| api/v1/management/secrets | GET | Returns entire secrets configuration (secret values will be masked by *s) |
```

2022-06-21 04:37 UTC, rmuolic commented on shared-content/management/secrets.md
> +| api/v1/management/secrets | GET | Returns entire secrets configuration (secret values will be *s) |
@akiaei - Let's use "hidden" rather than "masked".

2022-06-22 16:30 UTC, rmuolic approved these changes

2022-06-22 17:08 UTC, merged