Added description of behavior changes in automatic history recovery when client failover is enabled
osisoft/PI-Adapter pull request #114
Opened 2022-07-13 17:13 UTC by bningOSI

Hi Team,

This PR added a session in the automatic history recovery page to describe the behavior changes when client failover is enabled in  supported adapters.

2022-07-13 21:21 UTC, rmuolic commented on shared-content/configuration/history-recovery/automatic-history-recovery.md
> +- When client failover is disabled, the automatic history recovery works as described in [Automatic history recovery](#automatic-history-recovery) without any behavvior changes.
```suggestion
- When client failover is disabled, the automatic history recovery works as described in [Automatic history recovery](#automatic-history-recovery) without any behavior changes.
```

2022-07-13 21:29 UTC, rmuolic commented on shared-content/configuration/history-recovery/automatic-history-recovery.md
> +  - The adapter with failover role changed from `Primary` to `Secondary` stops tracking all open intervals and close them all.
```suggestion
- When client failover is enabled, automatic history recovery is affected as listed below.
  - The tracking of **DeviceStatus**, creation of history recovery intervals and automatic data backfill only occurs when the adapter is in the `Primary` role. 
  - The adapter does not track the `Shutdown` of the adapter to create a new history recovery interval.
  - The adapter with its failover role changed from `Primary` to `Secondary` stops tracking all open intervals and closes them all.
```

2022-07-13 21:30 UTC, rmuolic requested changes
Minor feedback provided.

2022-07-13 22:22 UTC, aveva-jhwang commented on shared-content/configuration/history-recovery/automatic-history-recovery.md
> +  - The adapter with failover role changed from `Primary` to `Secondary` stops tracking all open intervals and close them all.
From your modification suggestions, I have a few more that I'd like to suggest:
- The tracking of **DeviceStatus**, creation of history recovery intervals, and automatic data backfill only occur when the adapter is in the `Primary` role. _[changes made: added Oxford comma and removed the s in "occurs"]_
- The adapter does not track the `Shutdown` status of the adapter to create a new history recovery interval. _[changes made: added the term "status"]_
- The adapter, with its failover role changed from `Primary` to `Secondary`, stops tracking all open intervals and closes them all. _[changes made: added commas to separate out the behavior from causation]_

2022-07-14 07:04 UTC, zryska commented on shared-content/configuration/history-recovery/automatic-history-recovery.md
> +  - The adapter with failover role changed from `Primary` to `Secondary` stops tracking all open intervals and close them all.
I like the suggestion! We might consider adding the following:
 - The adapter attempts to recover data for existing intervals only in the `Primary` role.

2022-07-14 16:29 UTC, rmuolic approved these changes

2022-07-14 16:33 UTC, aveva-jhwang approved these changes

2022-07-14 19:26 UTC, merged