Read-only configuration facets not returned
osisoft/PI-Adapter pull request #115
Opened 2022-07-26 11:49 UTC by zryska

This adds information about handling of read-only facets on the root configuration controller level.

2022-07-26 18:07 UTC, aveva-jhwang commented on shared-content/configuration/system-and-adapter.md
> +You can retrieve the configuration of, and configure the system component and adapter components together using a single file.
Maybe we can change the wording to: "You can retrieve and modify the configuration of the system component and adapter components together using a single file." ? If "modify" isn't the best word choice, we can adjust it.

2022-07-26 18:08 UTC, aveva-jhwang commented on shared-content/configuration/system-and-adapter.md
> +The entire application can be retrieved by issuing the following cURL command:
Do we want to specify "The entire application configuration"?

2022-07-26 18:50 UTC, zryska commented on shared-content/configuration/system-and-adapter.md
> +You can retrieve the configuration of, and configure the system component and adapter components together using a single file.
That's perfect! I changed the word modify to set. I am happy to adjust further if needed.

2022-07-26 18:51 UTC, zryska commented on shared-content/configuration/system-and-adapter.md
> +The entire application can be retrieved by issuing the following cURL command:
Great catch! Fixed. Thank you, Jiyeon!

2022-07-28 16:29 UTC, rmuolic commented on shared-content/configuration/system-and-adapter.md
> +The entire application can be retrieved by issuing the following cURL command:
```suggestion
The entire application can be retrieved by entering the following cURL command:
```

2022-07-28 16:39 UTC, rmuolic requested changes
Minor suggestion noted in my review. I've also changed the base branch to v1.6.

2022-08-03 19:35 UTC, zryska commented on shared-content/configuration/system-and-adapter.md
> +The entire application can be retrieved by issuing the following cURL command:
I like the suggestion! Please feel free to add it in.

2022-08-03 22:35 UTC, rmuolic approved these changes

2022-08-04 16:32 UTC, merged