336636 secrets doc cleanup
osisoft/PI-Adapter pull request #116
Opened 2022-07-26 18:06 UTC by akiaei01

Cleaning up extra quotation marks and commas and fixing typos. 
Documenting slight behavior change - Any curly braces anywhere in the secret Id are not allowed (previously documented was leading or trailing curly braces)
Also added default value information to expirationDate and Description in Secrets.md as well as format examples for datetime

2022-07-26 18:24 UTC, aveva-jhwang commented on shared-content/management/secrets.md
> +| **Id**              | Required | 'string' | Id of configuration to be added, edited, or removed. <br><br>Allowed value: any string that does not contain curly braces <br>(e.g., `<secretId>` is acce
I doubt anyone would have curly braces in the middle of the Id string but is that scenario supported? If so, maybe the wording for this should be: "any string that is not bound by curly braces"

2022-07-26 18:27 UTC, aveva-jhwang commented on shared-content/management/secrets.md
> +| **ExpirationDate** | Optional | 'datetime' | Expiration date of the secret. <br><br> Allowed value: any Json DateTime string <br> Examples of allowed formats:  UTC: `yyyy-mm-ddThh:mm:ssZ`; Local: `
I think the sentence flows better when you have it in this order: "The Description field is metadata and not used in the adapter." Same for the ExpirationDate field as well.

2022-07-26 18:28 UTC, akiaei01 commented on shared-content/management/secrets.md
> +| **Id**              | Required | 'string' | Id of configuration to be added, edited, or removed. <br><br>Allowed value: any string that does not contain curly braces <br>(e.g., `<secretId>` is acce
This is what we mentioned in that long talk after standup, curly braces anywhere in the ID should not be allowed. so `Secret{Value`, `{SecretValue}`, or `SecretValue}` would all not be allowed.
Unless you see a use case for a user wanting to have a curly brace somewhere in the middle of the Id string?

2022-07-26 18:29 UTC, aveva-jhwang commented on shared-content/management/secrets.md
> +| **ExpirationDate** | Optional | 'datetime' | Expiration date of the secret. <br><br> Allowed value: any Json DateTime string <br> Examples of allowed formats:  UTC: `yyyy-mm-ddThh:mm:ssZ`; Local: `
Regarding the allowed formats for the date, are these the only formats supported? If so, I'd reword it to "Allowed formats: UTC ....". If others are allowed, I would link to the list of examples so that users can pick the one that works best for them.

2022-07-26 18:33 UTC, aveva-jhwang commented on shared-content/management/secrets.md
> +| **Id**              | Required | 'string' | Id of configuration to be added, edited, or removed. <br><br>Allowed value: any string that does not contain curly braces <br>(e.g., `<secretId>` is acce
I thought what you shared during standup was the case where a customer would have { } at the start and end of the Id string, not in between. Regardless, I still don't see any reason why customers would have curly braces in the middle of the string so I'm good with your changes. The examples listed could be adjusted to not make it seem like it's only for cases when you'd have it start and end with curly braces. Maybe that'd make the example too long...

2022-07-26 18:41 UTC, aveva-jhwang commented on shared-content/management/secrets.md
> +	  "ExpirationDate": "2024-06-17",
Is there a reason this example was changed? In the description in the table, the allowed format example includes time information and the date format for local time is different. If this is a supported datetime format, does it expire at 23:59:59?

2022-07-26 18:46 UTC, akiaei01 commented on shared-content/management/secrets.md
> +| **Id**              | Required | 'string' | Id of configuration to be added, edited, or removed. <br><br>Allowed value: any string that does not contain curly braces <br>(e.g., `<secretId>` is acce
Hmm I think the wording is clear enough that there should not be any curly braces in the id string, and I'm not sure how to add another example that has a brace within it while still using the `<secretId>` format. What do you think @rmuolic ?

2022-07-26 18:51 UTC, kshuOSIsoft approved these changes

2022-07-26 18:56 UTC, akiaei01 commented on shared-content/management/secrets.md
> +	  "ExpirationDate": "2024-06-17",
Yes, the previous example does not actually work. If you do not specify the time, it defaults to 0, so `"2024-06-17T00:00:00"` in this case. 
Good catch, that was actually a copy-paste error from egress-endpoints.md, so I'll update that file as well. I just checked and putting a datetime in the format `mm-dd-yyyy hh:mm:ss` does not work in secrets or in egress-endpoints

2022-07-27 17:27 UTC, akiaei01 commented on shared-content/management/secrets.md
> +| **Id**              | Required | 'string' | Id of configuration to be added, edited, or removed. <br><br>Allowed value: any string that does not contain curly braces <br>(e.g., `<secretId>` is acce
I made a slight change to add another not allowed example `<secret{Id>`, let me know what you think

2022-07-27 20:03 UTC, aveva-jhwang submitted a review, later dismissed
I'm good with the changes. We can always adjust as we get feedback from our customers. Thanks!

2022-07-27 20:18 UTC, rmuolic commented on shared-content/management/secrets.md
> +| **ExpirationDate** | Optional | 'datetime' | Expiration date of the secret. <br><br> Allowed formats:  UTC: `"yyyy-mm-ddThh:mm:ssZ"`; Local: `"yyyy-mm-ddThh:mm:ss"`. If the time not specified, it w
```suggestion
| **ExpirationDate** | Optional | 'datetime' | Expiration date of the secret. <br><br> Allowed formats:  UTC: `"yyyy-mm-ddThh:mm:ssZ"`; Local: `"yyyy-mm-ddThh:mm:ss"`. If the time is not specified, it will default to the start of the day (e.g. `2025-06-19` will default to `2025-06-19T00:00:00`) <br>Default: `null`<br> **Note:** The **ExpirationDate** field is metadata and not used in the adapter. |
```

2022-07-27 20:18 UTC, rmuolic commented on shared-content/management/secrets.md
> +| **Value** | Required | 'string' | The secret value. <br><br>Allowed value: any string that is not explicitly enclosed by double curly braces <br>(e.g.,  `<value>`, `{{{<value>}}`, or `{{<val{ue>}}`
```suggestion
| **Value** | Required | 'string' | The secret value. <br><br>Allowed value: any string that is not explicitly enclosed by double curly braces <br>(e.g., `<value>`, `{{{<value>}}`, or `{{<val{ue>}}` is acceptable but `{{<value>}}` is not)|
```

2022-07-27 20:19 UTC, rmuolic commented on shared-content/management/secrets.md
> +| api/v1/management/secrets/{sid} | GET | Returns single secret if exists (secret values will be hidden by *s) |
```suggestion
| api/v1/management/secrets/{sid} | GET | Returns a single secret if it exists (secret values will be hidden by *s) |
```

2022-07-27 20:21 UTC, rmuolic commented on shared-content/management/secrets/reference-secrets.md
> +> **Note:** The **Value** `<clientsecret>` is encrypted before storing in the secrets management configuration.
```suggestion
 **Note:** The **Value** `<clientsecret>` is encrypted before storing in the secrets management configuration.
```

2022-07-27 20:22 UTC, rmuolic commented on shared-content/troubleshooting/troubleshooting.md
> +If the time not specified, it will default to the start of the day (e.g. `2025-06-19` will default to `2025-06-19T00:00:00`)
```suggestion
If the time not specified, it will default to the start of the day (e.g., `2025-06-19` will default to `2025-06-19T00:00:00`)
```

2022-07-27 20:23 UTC, rmuolic commented on shared-content/configuration/health-endpoints.md
> +| **DebugExpiration** | Optional | string | Enables logging of detailed information, for each outbound HTTP request pertaining to this egress endpoint, to disk. The value represents the date and time
```suggestion
| **DebugExpiration** | Optional | string | Enables logging of detailed information, for each outbound HTTP request pertaining to this egress endpoint, to disk. The value represents the date and this detailed information should stop being saved. Examples of valid strings representing date and time: UTC: "yyyy-mm-ddThh:mm:ssZ", Local: "yyyy-mm-ddThh:mm:ss". For more information, see [Egress debug logging](xref:TroubleshootTheAdapter#egress-debug-logging).<br><br>Default: `null` |
```

2022-07-27 20:25 UTC, rmuolic commented on shared-content/configuration/egress-endpoints.md
> +| **DebugExpiration**             | Optional                  | string    | Enables logging of detailed information to disk for each outbound HTTP request pertaining to the egress endpoint. The value
```suggestion
| **DebugExpiration**             | Optional                  | string    | Enables logging of detailed information to disk for each outbound HTTP request pertaining to the egress endpoint. The value represents the date and time that this detailed information should stop being saved. Examples of valid strings representing date and time:  UTC: `yyyy-mm-ddThh:mm:ssZ`, Local: `yyyy-mm-ddThh:mm:ss`. For more information, see [Egress debug logging](xref:TroubleshootTheAdapter#egress-debug-logging).<br><br>Default: `null`|
```

2022-07-27 20:28 UTC, rmuolic requested changes
Minor corrections noted in suggestions.

2022-07-27 20:52 UTC, rmuolic approved these changes

2022-07-27 20:55 UTC, kshuOSIsoft approved these changes

2022-07-28 17:44 UTC, aveva-jhwang approved these changes

2022-07-28 18:00 UTC, merged