Added introduction and users topics
osisoft/PI-Adapter pull request #50
Opened 2021-01-20 00:49 UTC by TinaUll

Please review :)

2021-02-18 03:14 UTC, osisoft-mbishop requested changes
Nice job Tina! These documents are a good starting point that we can iterate through with Product Management. I have some suggestions, but most of them are nit-picks.

2021-02-18 03:14 UTC, osisoft-mbishop commented on V1/pi-adapter-users.md
> +Who uses PI Adapters and what do they use it for? With the PI Adapters' comprehensive amount of functions, they are applicable to a variety of users' work. Starting from the installation and configur
I think instead of concentrating on the "who" in this lead-in text, it would be more helpful to focus on the "where" and "what".

```suggestion
PI Adapters are typically used by users who:

- Operate in an edge environment 
- Operate on-premises but are interested in interpreting data from an edge environment
```

2021-02-18 23:08 UTC, TinaUll commented on V1/introduction-to-pi-adapters.md
> +PI Adapters incorporate robust data collection through buffering for data egressed from the adapter to egress endpoints or health endpoints. Buffering helps to overcome network and system disruptions
@osisoft-mbishop Hmm, your suggestion changes the meaning of the sentence

2021-02-18 23:55 UTC, TinaUll commented on V1/introduction-to-pi-adapters.md
> +The optional stream metadata capability provides the option to set the amount of metadata to provide meaningful metadata that differs for every adapter type.
@osisoft-mbishop How about this?
```suggestion
The optional stream metadata capability allows to set the amount of metadata sent with each stream. Metadata are different for every adapter type.
```

2021-02-19 02:52 UTC, osisoft-mbishop commented on V1/introduction-to-pi-adapters.md
> +PI Adapters incorporate robust data collection through buffering for data egressed from the adapter to egress endpoints or health endpoints. Buffering helps to overcome network and system disruptions
@TinaUll , I was just floating a suggestion because I didn't understand the first sentence. "incorporate robust data collection" sounds generic. Feel free to decline.

2021-02-19 03:00 UTC, osisoft-mbishop commented on V1/introduction-to-pi-adapters.md
> +The optional stream metadata capability provides the option to set the amount of metadata to provide meaningful metadata that differs for every adapter type.
I like that! :thumbsup:

It's missing a "you", but otherwise that's much more elegant than my suggestion:

>The optional stream metadata capability allows **you** to set the amount of metadata sent with each stream. Metadata are different for every adapter type.

2021-02-19 03:01 UTC, osisoft-mbishop approved these changes

2021-02-19 16:40 UTC, TinaUll commented on V1/introduction-to-pi-adapters.md
> +The optional stream metadata capability provides the option to set the amount of metadata to provide meaningful metadata that differs for every adapter type.
Great, thanks!

2021-02-19 16:47 UTC, merged