Create text-parser.md
osisoft/PI-Adapter pull request #57
Opened 2021-02-25 00:52 UTC by TinaUll

Hey @osisoft-mbishop, I drafted the new Text Parser framework topic. I would be grateful if you could take a quick look and let me know about anything that is not clear or missing. (The error handling section might or might not be removed). Thank you!

2021-02-25 02:33 UTC, osisoft-mbishop commented
@TinaUll , sure, I'll look tomorrow.

2021-02-26 00:55 UTC, osisoft-mbishop requested changes
Hi Tina,

I took look at the text parser wiki, and a few important pieces of information are missing from this doc. There's more info about this comment in my inline comments.

One general comment: we should add a heading somewhere that states what configuration file/endpoint is used to set XPATH/JSONpath/CSV options for the text parser. We may need to go back to the developer for more info.

2021-02-26 00:55 UTC, osisoft-mbishop commented on V1.3/Text Parser/text-parser.md
> +The adapter you are using includes the Text Parser component which ensures consistent parsing of text from XML, JSON, and CSV files. Designed to be a document parser, the Text Parser parses a semanti
The first sentence needs a comma. I think in the second sentence, you should cut the subordinate clause:

```suggestion
The adapter you are using includes the Text Parser component, which ensures consistent parsing of text from XML, JSON, and CSV files. The Text Parser parses a semantically complete document in its entirety.
```

2021-02-26 00:55 UTC, osisoft-mbishop commented on V1.3/Text Parser/text-parser.md
> +If a time zone supports time changes between daylight and standard times, the text file source might contain invalid or ambiguous datetimes. These are usually only possible for a two hour period each
In the second sentence, I'm not clear what "These" is referring to: the time gap or the invalid datetime. I think you're referring to the invalid datetime, so here's my suggestion: 

```suggestion
If a time zone supports time changes between daylight and standard times, the text file source might contain invalid or ambiguous datetimes. These invalid datetimes are usually only possible for a two-hour period each year because they occur during time changes. Ambiguous times are reported as standard times.
```

2021-02-26 00:55 UTC, osisoft-mbishop commented on V1.3/Text Parser/text-parser.md
> +## Syntaxes for value retrieval
Based on the wiki pages, I think what the developer was going for was to:

1. Display a text document in whatever format (JSON, XML, CSV) that shows the data that a user would want to capture. 
2. Show a configuration example of how to catch that data. I think this is the part he wants to emphasize for users.  The configurations are providing the JSONpath and XPath examples for parsing the data. 

We might want to sync with the dev here, but I suggest copy/pasting everything he's written in its entirety.

2021-02-26 00:55 UTC, osisoft-mbishop commented on V1.3/Text Parser/text-parser.md
> +
I think we should include this heading from the wiki, which is a list of datatypes that the text parser can handle: 

https://dev.azure.com/osieng/engineering/_wiki/wikis/AdapterFramework.wiki/12309/Value-Extraction-And-Conversion?anchor=data-types-supported-by-the-text-parser

2021-03-01 12:56 UTC, jfnoss requested changes
I would suggest adding some XPath and JSONPath examples for how to retrieve information from the sample files in the documentation. An example for XPath from the existing internal developer documentation: XPath configuration to read a series of values:

{
    "Id": "DoubleValue",
    "FieldDefinition": "./values/value/value",
    "DataType": "Double"
},
{
     "Id": "Timestamp",
    **"FieldDefinition": "./values/value/time",**
    "DataType": "DateTime",
    "IsIndex": true
}
JSONPath configuration to read a series of values:

{
    "Id": "DoubleValue",
    "FieldDefinition": "value",
    "DataType": "Double"
},
{
    "Id": "Timestamp",
    "FieldDefinition": "time",
    "DataType": "DateTime",
    "IsIndex": true
}

This example requires the text parser be configured with HasHeader=false. The column indexes are 1 based and configured as strings.

{
    "Id": "DoubleValue",
    "FieldDefinition": "2",
    "DataType": "Double"
},
{
    "Id": "Timestamp",
    "FieldDefinition": "1",
    "DataType": "DateTime",
    "IsIndex": true
}
This example requires the text parser be configured with HasHeader=true.

{
    "Id": "DoubleValue",
    "FieldDefinition": "Value",
    "DataType": "Double"
},
{
    "Id": "Timestamp",
    "FieldDefinition": "Date",
    "DataType": "DateTime",
    "IsIndex": true
}
The FieldDefinition in this example is the XPath expression. XPath, JSONPath, and CSV selection syntax will remain the same no matter which adapter is hosting the text parser, and it is where documenting the text parser will have the most value. The MQTT and Event Hub adapters will only support JSON and JSONPath, while the text parser is expected to support all three file types. It might make sense to partition the documentation so that JSONPath documentation can be shown without the other two so it could be used without the XML and CSV content for the event hub and MQTT Adapters.

2021-03-02 00:06 UTC, TinaUll commented on V1.3/Text Parser/jsonpath-syntax-for-value-retrieval.md
> +```
@jfnoss Would it be helpful to also include the complex example?

2021-03-02 00:18 UTC, jfnoss commented on V1.3/Text Parser/jsonpath-syntax-for-value-retrieval.md
> +```
I think more examples would be helpful. This will be the most challenging part of configuring a text based adapter.

2021-03-04 00:03 UTC, merged