Pbi 201375 and 201373 history recovery
osisoft/PI-Adapter pull request #63
Opened 2021-04-13 23:40 UTC by TinaUll

Hi @kshuOSIsoft and @osisoft-shillman - I drafted a few topics about history recovery. I based the content on the Design doc and the demo. Please take a look and let me know if this looks ok. 

For two of the parameters (checkpoint and items) I was not quite sure what to write. Maybe you can help me out there?! Thank you!

2021-04-14 00:07 UTC, osisoft-shillman requested changes
I only reviewed pieces related to auto HR; let me know if you have questions! Thank you.

2021-04-14 00:07 UTC, osisoft-shillman commented on shared-content/configuration/history-recovery/automatic-history-recovery.md
> +For automatic history recovery, the adapter keeps track of the components' **DeviceStatus** change to keep track of a list of periods to recover per component. The device states `DeviceInError` and `
Some suggested changes for flow, take it of leave it:

"For automatic history recovery, the adapter tracks changes to the **DeviceStatus** of each component. When the **DeviceStatus** changes to 'DeviceInError' or 'Shutdown', the adapter will start a new history recovery interval. When the issue resolves or the adapter is restarted and the **DeviceStatus** changes to 'Good', the adapter closes any current intervals for that component. The adapter tracks these intervals for each component and, when **DeviceStatus** has a value of 'Good', the adapter performs history recovery for these intervals starting from oldest to newest."

2021-04-14 00:07 UTC, osisoft-shillman commented on shared-content/configuration/history-recovery.md
> +- Limited (time-wise) automatic history recovery operation - backfills data gaps that originated from connection disruptions or PI adapter shutdown or both.
This also includes data source issues, not just connection issues. So we might want to say "...backfills data gaps that originated from connection disruptions, data source issues, and/or PI adapter shutdown."

2021-04-14 00:07 UTC, osisoft-shillman commented on shared-content/configuration/history-recovery.md
> +- Limited (time-wise) automatic history recovery operation - backfills data gaps that originated from connection disruptions or PI adapter shutdown or both.
I am being picky here, feel free to ignore. I feel like the "(time-wise)" part breaks up the bullet point. It might be better to say something like "Automatic history recovery operation -backfills data gaps ... or both. This is limited to a maximum time range of four days."

2021-04-15 16:37 UTC, kshuOSIsoft approved these changes

2021-04-15 16:37 UTC, kshuOSIsoft commented on shared-content/configuration/history-recovery.md
> +- On demand history recovery operation - start and end time specification required.
~start time is required. end time defaults to utc now if not specified.~
Actually if they don't put a time for start, it defaults to utcnow. if they don't put a time for endtime, it defaults to utcnow. Fails if startTime >= endtime (so they have to at least specify one of them)

2021-04-15 16:37 UTC, kshuOSIsoft commented on shared-content/configuration/history-recovery/on-demand-history-recovery-configuration.md
> +| api/v1/configuration/_<componentId>_/historyRecoveries/_<operationId>_ | DELETE       | Cancels history recovery
We've added a new route
/api/v1/configuration/{cid}/historyRecoveries/{oid}/cancel 
It cancels history recovery
All DELETEs will cancel and remove history recovery.

https://osisoft1980.sharepoint.com/:w:/t/Engineering/architecture/ER9oRoGHm0ROmvd1flensSEBl2l-_wUoEtpKP1gWB3F3BA?e=XppPFJ

2021-04-15 16:37 UTC, kshuOSIsoft commented on shared-content/configuration/history-recovery.md
> +- On demand history recovery operation - start and end time specification required.
I just checked the doc and there's one place that says it can't be null, and one place where it says that null = utcnow. I don't know what's supposed to be correct but the adapter behaves as stated above

2021-04-15 16:38 UTC, kshuOSIsoft requested changes
all these options confused me. Trying to change approve to request changes

2021-04-19 21:08 UTC, merged